### ISSUE TITLE
First TODO list

### ISSUE THREAD

**Issue by DraTeots** [DraTeots/trd_rec#1]
- [ ] Ask someone to reserve 25cm for TRD
- [ ] Look at support structure
- [ ] Fix overlaps
- [ ] Need de/dx information (micro TPC readout) and how to do a proper readout

- [ ] Path? 
    - [ ] Go with tracking only and GEM   
    - [ ] Add TRD part
